wordpress:
    image: wordpress
    links:
     - wordpress_db:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=oliviabarbeau
     - VIRTUAL_HOST=mysite.com
    ports:
     - "homelinux:80:80"
    volumes:
     - ./code:/code
     - ./html:/var/www/html/oliviabarbeau_wp
wordpress_db:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=oliviabarbeau
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: oliviabarbeau
