wordpress:
    image: wordpress
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=oliviabarbeau
    ports:
     - "homelinux:80:80"
    volumes:
     - ./code:/code
     - ./html:/var/www/html/oliviabarbeau
mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=oliviabarbeau
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql
